version: '3.8'

services:
#  db:
#    image: postgres:13.3
#    environment:
#      POSTGRES_DB: "boardgames"
#      POSTGRES_USER: "postgres"
#      POSTGRES_PASSWORD: "root"
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./src/main/resources/db/db-data:/var/lib/postgresql/data
#  pgadmin:
#    image: dpage/pgadmin4:7
#    user: root
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "5050:80"
#    volumes:
#      - ./src/main/resources/db/pgadmin-data:/var/lib/pgadmin


#  redis:
#    container_name: redis
#    hostname: redis
#    image: redis
#    ports:
#      - "6379:6379"
#  redis-commander:
#     container_name: redis-commander
#     hostname: redis-commander
#     image: rediscommander/redis-commander:latest
#     restart: always
#     environment:
#       - REDIS_HOSTS=local:redis:6379
#     ports:
#       - "8081:8081"

  client-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
#    depends_on:
#      - db
    environment:
#      - SERVER_PORT= 8888
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/boardgames

volumes:
  db-data:
  pgadmin-data: